version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: xxl_job
      MYSQL_USER: pyr
      MYSQL_PASSWORD: 123
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"